#!/usr/bin/env bash

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $against --

# Run autopep8
# https://stackoverflow.com/a/35420489
touched_python_files=$(git diff --cached --name-only | grep -E '\.py$')
if [ -n "$touched_python_files" ]; then
    options="\
      --ignore=E26 \
      --max-line-length=150 \
    "

    output=$(autopep8 -d $options "${touched_python_files[@]}")

    if [ -n "$output" ]; then
        autopep8 -i -j 0 $options "${touched_python_files[@]}"
        echo ">>> autopep8 edited some files <<<"
        exit 1
    fi
fi

if black --check .
then
	  echo "Formatting passed"
else
	  echo "Formatting failed."
	  exit 1
fi

if pytest
then
	  echo "Tests passed"
else
	  echo "Tests failed. Aborting commit."
	  exit 2
fi

if mypy ./main.py
then
	  echo "Main type-checks"
else
	  echo "Main fails type-checking with mypy. Aborting commit."
	  exit 3
fi

if ./main.py
then
	  echo "Main runs"
else
	  echo "Main failed. Aborting commit."
	  exit 4
fi
